//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
)

func main() {
	// The path to your PNG file. Change this as needed.
	const pngFilePath = "flatpak/io.github.essentialist_app.essentialist.png"
	// The name of the output Go file.
	const outputFilePath = "image_data.go"

	// 1. Read the PNG file into a byte slice.
	pngData, err := os.ReadFile(pngFilePath)
	if err != nil {
		log.Fatalf("failed to read PNG file %s: %v", pngFilePath, err)
	}

	// 2. Format the byte slice for a Go source file.
	// This creates a string representation like `[]byte{0x89, 0x50, 0x4e, ...}`
	var dataString string
	for _, b := range pngData {
		dataString += fmt.Sprintf("0x%02x,", b)
	}

	// 3. Create the content for the new Go file.
	fileContent := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package main

// IconBytes contains the raw byte data of the icon image.
var IconBytes = []byte{%s}
`, dataString)

	// 4. Write the content to the output file.
	err = os.WriteFile(outputFilePath, []byte(fileContent), 0644)
	if err != nil {
		log.Fatalf("failed to write Go file %s: %v", outputFilePath, err)
	}

	fmt.Printf("Successfully generated %s from %s\n", outputFilePath, pngFilePath)
}
